### PR TITLE
Add support for symfony 6 to support Laravel 9

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Review by patinthehat — CHANGES_REQUESTED** [review]
Thank you for this addition!  I've added a few of the missing typehints, but you'll need to add the rest when you have an opportunity - see [here](https://github.com/spatie/x-ray/runs/5163951367?check_suite_focus=true#step:8:13) for what's missing.

**Comment by colinmackinlay** [comment]
@lloricode @patinthehat can you look at this again/resubmit? My PR #5 was merged by @freekmurze so your #3 may now pass checks

**Comment by lloricode** [comment]
> @lloricode @patinthehat can you look at this again/resubmit? My PR #5 was merged by @freekmurze so your #3 may now pass checks

oh, will check later, thank you

**Comment by lloricode** [comment]
Closing this, already fix by #5 and able to use in laravel 9 with `composer require --dev spatie/x-ray:"dev-main"`

thanks @colinmackinlay @patinthehat

**Pull request closed without merging**
